create synonym BLCAmaint.shipped_biospecimen for tcgaBLCA.shipped_biospecimen;
create synonym BRCAmaint.shipped_biospecimen for tcgaBRCA.shipped_biospecimen;
create synonym CESCmaint.shipped_biospecimen for tcgaCESC.shipped_biospecimen;
create synonym COADmaint.shipped_biospecimen for tcgaCOAD.shipped_biospecimen;
create synonym DLBCmaint.shipped_biospecimen for tcgaDLBC.shipped_biospecimen;
create synonym GBMmaint.shipped_biospecimen for tcgaGBM.shipped_biospecimen;
create synonym HNSCmaint.shipped_biospecimen for tcgaHNSC.shipped_biospecimen;
create synonym KIRCmaint.shipped_biospecimen for tcgaKIRC.shipped_biospecimen;
create synonym KIRPmaint.shipped_biospecimen for tcgaKIRP.shipped_biospecimen;
create synonym LAMLmaint.shipped_biospecimen for tcgaLAML.shipped_biospecimen;
create synonym LCLLmaint.shipped_biospecimen for tcgaLCLL.shipped_biospecimen;
create synonym LGGmaint.shipped_biospecimen for tcgaLGG.shipped_biospecimen;
create synonym LIHCmaint.shipped_biospecimen for tcgaLIHC.shipped_biospecimen;
create synonym LNNHmaint.shipped_biospecimen for tcgaLNNH.shipped_biospecimen;
create synonym LUADmaint.shipped_biospecimen for tcgaLUAD.shipped_biospecimen;
create synonym LUSCmaint.shipped_biospecimen for tcgaLUSC.shipped_biospecimen;
create synonym OVmaint.shipped_biospecimen for tcgaOV.shipped_biospecimen;
create synonym PAADmaint.shipped_biospecimen for tcgaPAAD.shipped_biospecimen;
create synonym PRADmaint.shipped_biospecimen for tcgaPRAD.shipped_biospecimen;
create synonym READmaint.shipped_biospecimen for tcgaREAD.shipped_biospecimen;
create synonym SALDmaint.shipped_biospecimen for tcgaSALD.shipped_biospecimen;
create synonym SKCMmaint.shipped_biospecimen for tcgaSKCM.shipped_biospecimen;
create synonym STADmaint.shipped_biospecimen for tcgaSTAD.shipped_biospecimen;
create synonym THCAmaint.shipped_biospecimen for tcgaTHCA.shipped_biospecimen;
create synonym UCECmaint.shipped_biospecimen for tcgaUCEC.shipped_biospecimen;
create synonym BLCAmaint.shipped_biospecimen_element for tcgaBLCA.shipped_biospecimen_element;
create synonym BRCAmaint.shipped_biospecimen_element for tcgaBRCA.shipped_biospecimen_element;
create synonym CESCmaint.shipped_biospecimen_element for tcgaCESC.shipped_biospecimen_element;
create synonym COADmaint.shipped_biospecimen_element for tcgaCOAD.shipped_biospecimen_element;
create synonym DLBCmaint.shipped_biospecimen_element for tcgaDLBC.shipped_biospecimen_element;
create synonym GBMmaint.shipped_biospecimen_element for tcgaGBM.shipped_biospecimen_element;
create synonym HNSCmaint.shipped_biospecimen_element for tcgaHNSC.shipped_biospecimen_element;
create synonym KIRCmaint.shipped_biospecimen_element for tcgaKIRC.shipped_biospecimen_element;
create synonym KIRPmaint.shipped_biospecimen_element for tcgaKIRP.shipped_biospecimen_element;
create synonym LAMLmaint.shipped_biospecimen_element for tcgaLAML.shipped_biospecimen_element;
create synonym LCLLmaint.shipped_biospecimen_element for tcgaLCLL.shipped_biospecimen_element;
create synonym LGGmaint.shipped_biospecimen_element for tcgaLGG.shipped_biospecimen_element;
create synonym LIHCmaint.shipped_biospecimen_element for tcgaLIHC.shipped_biospecimen_element;
create synonym LNNHmaint.shipped_biospecimen_element for tcgaLNNH.shipped_biospecimen_element;
create synonym LUADmaint.shipped_biospecimen_element for tcgaLUAD.shipped_biospecimen_element;
create synonym LUSCmaint.shipped_biospecimen_element for tcgaLUSC.shipped_biospecimen_element;
create synonym OVmaint.shipped_biospecimen_element for tcgaOV.shipped_biospecimen_element;
create synonym PAADmaint.shipped_biospecimen_element for tcgaPAAD.shipped_biospecimen_element;
create synonym PRADmaint.shipped_biospecimen_element for tcgaPRAD.shipped_biospecimen_element;
create synonym READmaint.shipped_biospecimen_element for tcgaREAD.shipped_biospecimen_element;
create synonym SALDmaint.shipped_biospecimen_element for tcgaSALD.shipped_biospecimen_element;
create synonym SKCMmaint.shipped_biospecimen_element for tcgaSKCM.shipped_biospecimen_element;
create synonym STADmaint.shipped_biospecimen_element for tcgaSTAD.shipped_biospecimen_element;
create synonym THCAmaint.shipped_biospecimen_element for tcgaTHCA.shipped_biospecimen_element;
create synonym UCECmaint.shipped_biospecimen_element for tcgaUCEC.shipped_biospecimen_element;
create synonym BLCAmaint.shipped_biospec_bcr_archive  for tcgaBLCA.shipped_biospec_bcr_archive ;
create synonym BRCAmaint.shipped_biospec_bcr_archive  for tcgaBRCA.shipped_biospec_bcr_archive ;
create synonym CESCmaint.shipped_biospec_bcr_archive  for tcgaCESC.shipped_biospec_bcr_archive ;
create synonym COADmaint.shipped_biospec_bcr_archive  for tcgaCOAD.shipped_biospec_bcr_archive ;
create synonym DLBCmaint.shipped_biospec_bcr_archive  for tcgaDLBC.shipped_biospec_bcr_archive ;
create synonym GBMmaint.shipped_biospec_bcr_archive  for tcgaGBM.shipped_biospec_bcr_archive ;
create synonym HNSCmaint.shipped_biospec_bcr_archive  for tcgaHNSC.shipped_biospec_bcr_archive ;
create synonym KIRCmaint.shipped_biospec_bcr_archive  for tcgaKIRC.shipped_biospec_bcr_archive ;
create synonym KIRPmaint.shipped_biospec_bcr_archive  for tcgaKIRP.shipped_biospec_bcr_archive ;
create synonym LAMLmaint.shipped_biospec_bcr_archive  for tcgaLAML.shipped_biospec_bcr_archive ;
create synonym LCLLmaint.shipped_biospec_bcr_archive  for tcgaLCLL.shipped_biospec_bcr_archive ;
create synonym LGGmaint.shipped_biospec_bcr_archive  for tcgaLGG.shipped_biospec_bcr_archive ;
create synonym LIHCmaint.shipped_biospec_bcr_archive  for tcgaLIHC.shipped_biospec_bcr_archive ;
create synonym LNNHmaint.shipped_biospec_bcr_archive  for tcgaLNNH.shipped_biospec_bcr_archive ;
create synonym LUADmaint.shipped_biospec_bcr_archive  for tcgaLUAD.shipped_biospec_bcr_archive ;
create synonym LUSCmaint.shipped_biospec_bcr_archive  for tcgaLUSC.shipped_biospec_bcr_archive ;
create synonym OVmaint.shipped_biospec_bcr_archive  for tcgaOV.shipped_biospec_bcr_archive ;
create synonym PAADmaint.shipped_biospec_bcr_archive  for tcgaPAAD.shipped_biospec_bcr_archive ;
create synonym PRADmaint.shipped_biospec_bcr_archive  for tcgaPRAD.shipped_biospec_bcr_archive ;
create synonym READmaint.shipped_biospec_bcr_archive  for tcgaREAD.shipped_biospec_bcr_archive ;
create synonym SALDmaint.shipped_biospec_bcr_archive  for tcgaSALD.shipped_biospec_bcr_archive ;
create synonym SKCMmaint.shipped_biospec_bcr_archive  for tcgaSKCM.shipped_biospec_bcr_archive ;
create synonym STADmaint.shipped_biospec_bcr_archive  for tcgaSTAD.shipped_biospec_bcr_archive ;
create synonym THCAmaint.shipped_biospec_bcr_archive  for tcgaTHCA.shipped_biospec_bcr_archive ;
create synonym UCECmaint.shipped_biospec_bcr_archive  for tcgaUCEC.shipped_biospec_bcr_archive ;
create synonym BLCAmaint.shipped_biospecimen_file  for tcgaBLCA.shipped_biospecimen_file ;
create synonym BRCAmaint.shipped_biospecimen_file  for tcgaBRCA.shipped_biospecimen_file ;
create synonym CESCmaint.shipped_biospecimen_file  for tcgaCESC.shipped_biospecimen_file ;
create synonym COADmaint.shipped_biospecimen_file  for tcgaCOAD.shipped_biospecimen_file ;
create synonym DLBCmaint.shipped_biospecimen_file  for tcgaDLBC.shipped_biospecimen_file ;
create synonym GBMmaint.shipped_biospecimen_file  for tcgaGBM.shipped_biospecimen_file ;
create synonym HNSCmaint.shipped_biospecimen_file  for tcgaHNSC.shipped_biospecimen_file ;
create synonym KIRCmaint.shipped_biospecimen_file  for tcgaKIRC.shipped_biospecimen_file ;
create synonym KIRPmaint.shipped_biospecimen_file  for tcgaKIRP.shipped_biospecimen_file ;
create synonym LAMLmaint.shipped_biospecimen_file  for tcgaLAML.shipped_biospecimen_file ;
create synonym LCLLmaint.shipped_biospecimen_file  for tcgaLCLL.shipped_biospecimen_file ;
create synonym LGGmaint.shipped_biospecimen_file  for tcgaLGG.shipped_biospecimen_file ;
create synonym LIHCmaint.shipped_biospecimen_file  for tcgaLIHC.shipped_biospecimen_file ;
create synonym LNNHmaint.shipped_biospecimen_file  for tcgaLNNH.shipped_biospecimen_file ;
create synonym LUADmaint.shipped_biospecimen_file  for tcgaLUAD.shipped_biospecimen_file ;
create synonym LUSCmaint.shipped_biospecimen_file  for tcgaLUSC.shipped_biospecimen_file ;
create synonym OVmaint.shipped_biospecimen_file  for tcgaOV.shipped_biospecimen_file ;
create synonym PAADmaint.shipped_biospecimen_file  for tcgaPAAD.shipped_biospecimen_file ;
create synonym PRADmaint.shipped_biospecimen_file  for tcgaPRAD.shipped_biospecimen_file ;
create synonym READmaint.shipped_biospecimen_file  for tcgaREAD.shipped_biospecimen_file ;
create synonym SALDmaint.shipped_biospecimen_file  for tcgaSALD.shipped_biospecimen_file ;
create synonym SKCMmaint.shipped_biospecimen_file  for tcgaSKCM.shipped_biospecimen_file ;
create synonym STADmaint.shipped_biospecimen_file  for tcgaSTAD.shipped_biospecimen_file ;
create synonym THCAmaint.shipped_biospecimen_file  for tcgaTHCA.shipped_biospecimen_file ;
create synonym UCECmaint.shipped_biospecimen_file  for tcgaUCEC.shipped_biospecimen_file ;
create synonym commonmaint.shipped_biospecimen_file  for dcccommon.shipped_biospecimen_file ;
create synonym commonmaint.shipped_biospec_bcr_archive  for dcccommon.shipped_biospec_bcr_archive ;
create synonym commonmaint.shipped_biospecimen  for dcccommon.shipped_biospecimen ;
create synonym commonmaint.shipped_biospecimen_element  for dcccommon.shipped_biospecimen_element ;
create synonym commonmaint.shipped_element_type  for dcccommon.shipped_element_type ;
create synonym commonmaint.shipped_item_type  for dcccommon.shipped_item_type ;
create synonym commonmaint.shipped_element for dcccommon.shipped_element ;
create synonym commonmaint.shipped_biospecimen  for dcccommon.shipped_biospecimen ;


