INSERT INTO PLATFORM (PLATFORM_ID, PLATFORM_NAME, PLATFORM_DISPLAY_NAME, PLATFORM_ALIAS, 
CENTER_TYPE_CODE, SORT_ORDER, AVAILABLE, BASE_DATA_TYPE_ID)
VALUES (62, 'Mixed_DNASeq', 'Mixed Sequencing DNASeq Somatic Mutations', 'Mutation Calling', 'GSC', 62, 1, 7);

INSERT INTO PLATFORM (PLATFORM_ID, PLATFORM_NAME, PLATFORM_DISPLAY_NAME, PLATFORM_ALIAS, 
CENTER_TYPE_CODE, SORT_ORDER, AVAILABLE, BASE_DATA_TYPE_ID)
VALUES (63, 'Mixed_DNASeq_Cont', 'Mixed Sequencing DNASeq Controlled Mutations', 'Mutation Calling', 'GSC', 63, 1, 41);

INSERT INTO DATA_TYPE_TO_PLATFORM (DATA_TYPE_PLATFORM_ID, DATA_TYPE_ID, PLATFORM_ID)
VALUES(152, 7, 62);

INSERT INTO DATA_TYPE_TO_PLATFORM (DATA_TYPE_PLATFORM_ID, DATA_TYPE_ID, PLATFORM_ID)
VALUES(153, 41, 63);

COMMIT;