-- add elapsed time fields to clinical files on DAM, and remove specific date fields from all files

delete from clinical_file_element where FILE_COLUMN_NAME like 'DAYOF%';
delete from clinical_file_element where FILE_COLUMN_NAME like 'MONTHOF%';
delete from clinical_file_element where FILE_COLUMN_NAME like 'YEAROF%';
delete from clinical_file_element where FILE_COLUMN_NAME='DATEOFCOLLECTION';


insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(183, 'DAYSTOBIRTH', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 183, 1, 'DAYSTOBIRTH', 'DAYSTOBIRTH', 8, 1);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(184, 'DAYSTODEATH', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 184, 1, 'DAYSTODEATH', 'DAYSTODEATH', 11, 1);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(185, 'DAYSTOLASTFOLLOWUP', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 185, 1, 'DAYSTOLASTFOLLOWUP', 'DAYSTOLASTFOLLOWUP', 14, 1);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(186, 'DAYSTOTUMORPROGRESSION', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 186, 1, 'DAYSTOTUMORPROGRESSION', 'DAYSTOTUMORPROGRESSION', 27, 1);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(187, 'DAYSTOTUMORRECURRENCE', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 187, 1, 'DAYSTOTUMORRECURRENCE', 'DAYSTOTUMORRECURRENCE', 30, 1);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(188, 'AGEATINITIALPATHOLOGICDIAGNOSIS', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 188, 1, 'AGEATINITPATHOLOGICDIAGNOSIS', 'AGEATINITIALPATHOLOGICDIAGNOSIS', 19, 1);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(189, 'DAYSTOCOLLECTION', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 189, 2, 'DAYSTOCOLLECTION', 'DAYSTOCOLLECTION', 22, 2);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(190, 'DAYSTODRUGTREATMENTSTART', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 190, 15, 'DAYSTODRUGTREATMENTSTART', 'DAYSTODRUGTREATMENTSTART', 5, 10);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(191, 'DAYSTODRUGTREATMENTEND', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 191, 15, 'DAYSTODRUGTREATMENTEND', 'DAYSTODRUGTREATMENTEND', 8, 10);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(192, 'DAYSTORADIATIONTREATMENTSTART', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 192, 13, 'DAYSTORADIATIONTREATMENTSTART', 'DAYSTORADIATIONTREATMENTSTART', 1, 12);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(193, 'DAYSTORADIATIONTREATMENTEND', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 193, 13, 'DAYSTORADIATIONTREATMENTEND', 'DAYSTORADIATIONTREATMENTEND', 4, 12);

insert into CLINICAL_XSD_ELEMENT(CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED)
        VALUES(194, 'DAYSTOPROCEDURE', 0);
insert into CLINICAL_FILE_ELEMENT(CLINICAL_FILE_ELEMENT_ID, XSD_ELEMENT_ID, TABLE_ID, TABLE_COLUMN_NAME, FILE_COLUMN_NAME, FILE_COLUMN_ORDER, CLINICAL_FILE_ID)
        VALUES(CLINICAL_FILE_ELEMENT_SEQ.nextval, 194, 14, 'DAYSTOPROCEDURE', 'DAYSTOPROCEDURE', 1, 13);

delete from clinical_file_element where file_column_name='REVISION';
delete from clinical_file_element where file_column_name='BCRSITEID';