
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_additional_surgery_locoregional_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_additional_surgery_metastatic_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_birth', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_collection', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_death', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_drug_therapy_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_drug_therapy_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_drug_treatment_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_drug_treatment_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_form_completion', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_initial_pathologic_diagnosis', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_last_followup', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_last_known_alive', 1,'','integer','N' from clinical_xsd_element);

insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_new_tumor_event_after_initial_treatment', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_radiation_therapy_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_radiation_therapy_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_radiation_treatment_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_radiation_treatment_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_sample_procurement', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_tumor_progression', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'day_of_tumor_recurrence', 1,'','integer','N' from clinical_xsd_element);

insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_additional_surgery_locoregional_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_additional_surgery_metastatic_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_birth', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_collection', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_death', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_drug_therapy_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_drug_therapy_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_drug_treatment_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_drug_treatment_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_form_completion', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_initial_pathologic_diagnosis', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_last_followup', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_last_known_alive', 1,'','integer','N' from clinical_xsd_element);

insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_new_tumor_event_after_initial_treatment', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_radiation_therapy_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_radiation_therapy_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_radiation_treatment_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_radiation_treatment_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_sample_procurement', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_tumor_progression', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'month_of_tumor_recurrence', 1,'','integer','N' from clinical_xsd_element);

insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_additional_surgery_locoregional_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_additional_surgery_metastatic_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_birth', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_collection', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_death', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_drug_therapy_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_drug_therapy_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_drug_treatment_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_drug_treatment_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_form_completion', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_initial_pathologic_diagnosis', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_last_followup', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_last_known_alive', 1,'','integer','N' from clinical_xsd_element);

insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_new_tumor_event_after_initial_treatment', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_procedure', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_radiation_therapy_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_radiation_therapy_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_radiation_treatment_end', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_radiation_treatment_start', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_sample_procurement', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_tumor_progression', 1,'','integer','N' from clinical_xsd_element);
insert into clinical_xsd_element (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE, expected_element) (select max(CLINICAL_XSD_ELEMENT_ID)+1,'year_of_tumor_recurrence', 1,'','integer','N' from clinical_xsd_element);

commit;
