---
abstract: 'Validator for JSON-format BCR dashboard reports'
author:
  - 'Mark A. Jensen'
build_requires:
  IPC::Run3: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: jsonval
provides:
  JSONVal::Configure:
    file: lib/JSONVal/Configure.pm
    version: 1.3
requires:
  JSON: 2.26
  Scalar::Util: 0
  perl: 5.008
version: 1.3
