CREATE USER tcgatest1 IDENTIFIED BY "tcga01unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest1;

GRANT CREATE PROCEDURE TO tcgatest1;

GRANT CREATE SEQUENCE TO tcgatest1;

GRANT CREATE SESSION TO tcgatest1;

GRANT CREATE SYNONYM TO tcgatest1;

GRANT CREATE TABLE TO tcgatest1;

GRANT CREATE TRIGGER TO tcgatest1;

GRANT CREATE VIEW TO tcgatest1;


GRANT "CONNECT" TO tcgatest1;
ALTER USER tcgatest1 DEFAULT ROLE NONE;

CREATE USER tcgatest2 IDENTIFIED BY "tcga02unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest2;

GRANT CREATE PROCEDURE TO tcgatest2;

GRANT CREATE SEQUENCE TO tcgatest2;

GRANT CREATE SESSION TO tcgatest2;

GRANT CREATE SYNONYM TO tcgatest2;

GRANT CREATE TABLE TO tcgatest2;

GRANT CREATE TRIGGER TO tcgatest2;

GRANT CREATE VIEW TO tcgatest2;


GRANT "CONNECT" TO tcgatest2;
ALTER USER tcgatest2 DEFAULT ROLE NONE;
CREATE USER tcgatest3 IDENTIFIED BY "tcga03unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest3;

GRANT CREATE PROCEDURE TO tcgatest3;

GRANT CREATE SEQUENCE TO tcgatest3;

GRANT CREATE SESSION TO tcgatest3;

GRANT CREATE SYNONYM TO tcgatest3;

GRANT CREATE TABLE TO tcgatest3;

GRANT CREATE TRIGGER TO tcgatest3;

GRANT CREATE VIEW TO tcgatest3;


GRANT "CONNECT" TO tcgatest3;
ALTER USER tcgatest3 DEFAULT ROLE NONE;

CREATE USER tcgatest4 IDENTIFIED BY "test04unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest4;

GRANT CREATE PROCEDURE TO tcgatest4;

GRANT CREATE SEQUENCE TO tcgatest4;

GRANT CREATE SESSION TO tcgatest4;

GRANT CREATE SYNONYM TO tcgatest4;

GRANT CREATE TABLE TO tcgatest4;

GRANT CREATE TRIGGER TO tcgatest4;

GRANT CREATE VIEW TO tcgatest4;


GRANT "CONNECT" TO tcgatest4;
ALTER USER tcgatest4 DEFAULT ROLE NONE;

CREATE USER tcgatest5 IDENTIFIED BY "tcga05unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest5;

GRANT CREATE PROCEDURE TO tcgatest5;

GRANT CREATE SEQUENCE TO tcgatest5;

GRANT CREATE SESSION TO tcgatest5;

GRANT CREATE SYNONYM TO tcgatest5;

GRANT CREATE TABLE TO tcgatest5;

GRANT CREATE TRIGGER TO tcgatest5;

GRANT CREATE VIEW TO tcgatest5;


GRANT "CONNECT" TO tcgatest5;
ALTER USER tcgatest5 DEFAULT ROLE NONE;

CREATE USER tcgatest6 IDENTIFIED BY "tcga06unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest6;

GRANT CREATE PROCEDURE TO tcgatest6;

GRANT CREATE SEQUENCE TO tcgatest6;

GRANT CREATE SESSION TO tcgatest6;

GRANT CREATE SYNONYM TO tcgatest6;

GRANT CREATE TABLE TO tcgatest6;

GRANT CREATE TRIGGER TO tcgatest6;

GRANT CREATE VIEW TO tcgatest6;


GRANT "CONNECT" TO tcgatest6;
ALTER USER tcgatest6 DEFAULT ROLE NONE;

CREATE USER tcgatest7 IDENTIFIED BY "tcga07unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest7;

GRANT CREATE PROCEDURE TO tcgatest7;

GRANT CREATE SEQUENCE TO tcgatest7;

GRANT CREATE SESSION TO tcgatest7;

GRANT CREATE SYNONYM TO tcgatest7;

GRANT CREATE TABLE TO tcgatest7;

GRANT CREATE TRIGGER TO tcgatest7;

GRANT CREATE VIEW TO tcgatest7;


GRANT "CONNECT" TO tcgatest7;
ALTER USER tcgatest7 DEFAULT ROLE NONE;

CREATE USER tcgatest8 IDENTIFIED BY "tcga08unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest8;

GRANT CREATE PROCEDURE TO tcgatest8;

GRANT CREATE SEQUENCE TO tcgatest8;

GRANT CREATE SESSION TO tcgatest8;

GRANT CREATE SYNONYM TO tcgatest8;

GRANT CREATE TABLE TO tcgatest8;

GRANT CREATE TRIGGER TO tcgatest8;

GRANT CREATE VIEW TO tcgatest8;


GRANT "CONNECT" TO tcgatest8;
ALTER USER tcgatest8 DEFAULT ROLE NONE;

CREATE USER tcgatest9 IDENTIFIED BY "tcga09unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest9;

GRANT CREATE PROCEDURE TO tcgatest9;

GRANT CREATE SEQUENCE TO tcgatest9;

GRANT CREATE SESSION TO tcgatest9;

GRANT CREATE SYNONYM TO tcgatest9;

GRANT CREATE TABLE TO tcgatest9;

GRANT CREATE TRIGGER TO tcgatest9;

GRANT CREATE VIEW TO tcgatest9;


GRANT "CONNECT" TO tcgatest9;
ALTER USER tcgatest9 DEFAULT ROLE NONE;

CREATE USER tcgatest10 IDENTIFIED BY "tcga10unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest10;

GRANT CREATE PROCEDURE TO tcgatest10;

GRANT CREATE SEQUENCE TO tcgatest10;

GRANT CREATE SESSION TO tcgatest10;

GRANT CREATE SYNONYM TO tcgatest10;

GRANT CREATE TABLE TO tcgatest10;

GRANT CREATE TRIGGER TO tcgatest10;

GRANT CREATE VIEW TO tcgatest10;


GRANT "CONNECT" TO tcgatest10;
ALTER USER tcgatest10 DEFAULT ROLE NONE;


CREATE USER tcgatest11 IDENTIFIED BY "tcga11unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest11;

GRANT CREATE PROCEDURE TO tcgatest11;

GRANT CREATE SEQUENCE TO tcgatest11;

GRANT CREATE SESSION TO tcgatest11;

GRANT CREATE SYNONYM TO tcgatest11;

GRANT CREATE TABLE TO tcgatest11;

GRANT CREATE TRIGGER TO tcgatest11;

GRANT CREATE VIEW TO tcgatest11;


GRANT "CONNECT" TO tcgatest11;
ALTER USER tcgatest11 DEFAULT ROLE NONE;



CREATE USER tcgatest12 IDENTIFIED BY "tcga12unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest12;

GRANT CREATE PROCEDURE TO tcgatest12;

GRANT CREATE SEQUENCE TO tcgatest12;

GRANT CREATE SESSION TO tcgatest12;

GRANT CREATE SYNONYM TO tcgatest12;

GRANT CREATE TABLE TO tcgatest12;

GRANT CREATE TRIGGER TO tcgatest12;

GRANT CREATE VIEW TO tcgatest12;


GRANT "CONNECT" TO tcgatest12;
ALTER USER tcgatest12 DEFAULT ROLE NONE;



CREATE USER tcgatest13 IDENTIFIED BY "tcga13unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatest13;

GRANT CREATE PROCEDURE TO tcgatest13;

GRANT CREATE SEQUENCE TO tcgatest13;

GRANT CREATE SESSION TO tcgatest13;

GRANT CREATE SYNONYM TO tcgatest13;

GRANT CREATE TABLE TO tcgatest13;

GRANT CREATE TRIGGER TO tcgatest13;

GRANT CREATE VIEW TO tcgatest13;


GRANT "CONNECT" TO tcgatest13;
ALTER USER tcgatest13 DEFAULT ROLE NONE;



CREATE USER commontest IDENTIFIED BY "common01unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest;

GRANT CREATE PROCEDURE TO commontest;

GRANT CREATE SEQUENCE TO commontest;

GRANT CREATE SESSION TO commontest;

GRANT CREATE SYNONYM TO commontest;

GRANT CREATE TABLE TO commontest;

GRANT CREATE TRIGGER TO commontest;

GRANT CREATE VIEW TO commontest;


GRANT "CONNECT" TO commontest;

CREATE USER commontest2 IDENTIFIED BY "common02unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest2;

GRANT CREATE PROCEDURE TO commontest2;

GRANT CREATE SEQUENCE TO commontest2;

GRANT CREATE SESSION TO commontest2;

GRANT CREATE SYNONYM TO commontest2;

GRANT CREATE TABLE TO commontest2;

GRANT CREATE TRIGGER TO commontest2;

GRANT CREATE VIEW TO commontest2;

GRANT "CONNECT" TO commontest2;

CREATE USER commontest3 IDENTIFIED BY "common03unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest3;

GRANT CREATE PROCEDURE TO commontest3;

GRANT CREATE SEQUENCE TO commontest3;

GRANT CREATE SESSION TO commontest3;

GRANT CREATE SYNONYM TO commontest3;

GRANT CREATE TABLE TO commontest3;

GRANT CREATE TRIGGER TO commontest3;

GRANT CREATE VIEW TO commontest3;
grant connect to commontest3;

CREATE USER commontest2 IDENTIFIED BY "common02unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest2;

GRANT CREATE PROCEDURE TO commontest2;

GRANT CREATE SEQUENCE TO commontest2;

GRANT CREATE SESSION TO commontest2;

GRANT CREATE SYNONYM TO commontest2;

GRANT CREATE TABLE TO commontest2;

GRANT CREATE TRIGGER TO commontest2;

GRANT CREATE VIEW TO commontest2;


GRANT "CONNECT" TO commontest2;
CREATE USER commontest4 IDENTIFIED BY "common04unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest4;

GRANT CREATE PROCEDURE TO commontest4;

GRANT CREATE SEQUENCE TO commontest4;

GRANT CREATE SESSION TO commontest4;

GRANT CREATE SYNONYM TO commontest4;

GRANT CREATE TABLE TO commontest4;

GRANT CREATE TRIGGER TO commontest4;

GRANT CREATE VIEW TO commontest4;


GRANT "CONNECT" TO commontest4;

CREATE USER commontest5 IDENTIFIED BY "common05unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest5;

GRANT CREATE PROCEDURE TO commontest5;

GRANT CREATE SEQUENCE TO commontest5;

GRANT CREATE SESSION TO commontest5;

GRANT CREATE SYNONYM TO commontest5;

GRANT CREATE TABLE TO commontest5;

GRANT CREATE TRIGGER TO commontest5;

GRANT CREATE VIEW TO commontest5;


GRANT "CONNECT" TO commontest5;

CREATE USER commontest6 IDENTIFIED BY "common06unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest6;

GRANT CREATE PROCEDURE TO commontest6;

GRANT CREATE SEQUENCE TO commontest6;

GRANT CREATE SESSION TO commontest6;

GRANT CREATE SYNONYM TO commontest6;

GRANT CREATE TABLE TO commontest6;

GRANT CREATE TRIGGER TO commontest6;

GRANT CREATE VIEW TO commontest6;


GRANT "CONNECT" TO commontest6;

CREATE USER commontest7 IDENTIFIED BY "common07unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest7;

GRANT CREATE PROCEDURE TO commontest7;

GRANT CREATE SEQUENCE TO commontest7;

GRANT CREATE SESSION TO commontest7;

GRANT CREATE SYNONYM TO commontest7;

GRANT CREATE TABLE TO commontest7;

GRANT CREATE TRIGGER TO commontest7;

GRANT CREATE VIEW TO commontest7;


GRANT "CONNECT" TO commontest7;

CREATE USER commontest8 IDENTIFIED BY "common08unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest8;

GRANT CREATE PROCEDURE TO commontest8;

GRANT CREATE SEQUENCE TO commontest8;

GRANT CREATE SESSION TO commontest8;

GRANT CREATE SYNONYM TO commontest8;

GRANT CREATE TABLE TO commontest8;

GRANT CREATE TRIGGER TO commontest8;

GRANT CREATE VIEW TO commontest8;


GRANT "CONNECT" TO commontest8;

CREATE USER commontest9 IDENTIFIED BY "common09unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest9;

GRANT CREATE PROCEDURE TO commontest9;

GRANT CREATE SEQUENCE TO commontest9;

GRANT CREATE SESSION TO commontest9;

GRANT CREATE SYNONYM TO commontest9;

GRANT CREATE TABLE TO commontest9;

GRANT CREATE TRIGGER TO commontest9;

GRANT CREATE VIEW TO commontest9;


GRANT "CONNECT" TO commontest9;

CREATE USER commontest10 IDENTIFIED BY "common10unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest10;

GRANT CREATE PROCEDURE TO commontest10;

GRANT CREATE SEQUENCE TO commontest10;

GRANT CREATE SESSION TO commontest10;

GRANT CREATE SYNONYM TO commontest10;

GRANT CREATE TABLE TO commontest10;

GRANT CREATE TRIGGER TO commontest10;

GRANT CREATE VIEW TO commontest10;


CREATE USER commontest11 IDENTIFIED BY "common011unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest11;

GRANT CREATE PROCEDURE TO commontest11;

GRANT CREATE SEQUENCE TO commontest11;

GRANT CREATE SESSION TO commontest11;

GRANT CREATE SYNONYM TO commontest11;

GRANT CREATE TABLE TO commontest11;

GRANT CREATE TRIGGER TO commontest11;

GRANT CREATE VIEW TO commontest11;


GRANT "CONNECT" TO commontest11;


CREATE USER commontest12 IDENTIFIED BY "common012unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest12;

GRANT CREATE PROCEDURE TO commontest12;

GRANT CREATE SEQUENCE TO commontest12;

GRANT CREATE SESSION TO commontest12;

GRANT CREATE SYNONYM TO commontest12;

GRANT CREATE TABLE TO commontest12;

GRANT CREATE TRIGGER TO commontest12;

GRANT CREATE VIEW TO commontest12;


GRANT "CONNECT" TO commontest12;

CREATE USER commontest13 IDENTIFIED BY "common013unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commontest13;

GRANT CREATE PROCEDURE TO commontest13;

GRANT CREATE SEQUENCE TO commontest13;

GRANT CREATE SESSION TO commontest13;

GRANT CREATE SYNONYM TO commontest13;

GRANT CREATE TABLE TO commontest13;

GRANT CREATE TRIGGER TO commontest13;

GRANT CREATE VIEW TO commontest13;


GRANT "CONNECT" TO commontest13;

CREATE USER binftest IDENTIFIED BY "binf01test"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO binftest;

GRANT CREATE PROCEDURE TO binftest;

GRANT CREATE SEQUENCE TO binftest;

GRANT CREATE SESSION TO binftest;

GRANT CREATE SYNONYM TO binftest;

GRANT CREATE TABLE TO binftest;

GRANT CREATE TRIGGER TO binftest;

GRANT CREATE VIEW TO binftest;


GRANT "CONNECT" TO binftest;
ALTER USER binftest DEFAULT ROLE NONE;

CREATE USER commtestinteg IDENTIFIED BY "1nttestc0m"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO commtestinteg;

GRANT CREATE PROCEDURE TO commtestinteg;

GRANT CREATE SEQUENCE TO commtestinteg;

GRANT CREATE SESSION TO commtestinteg;

GRANT CREATE SYNONYM TO commtestinteg;

GRANT CREATE TABLE TO commtestinteg;

GRANT CREATE TRIGGER TO commtestinteg;

GRANT CREATE VIEW TO commtestinteg;


GRANT "CONNECT" TO commtestinteg;
ALTER USER commtestinteg DEFAULT ROLE NONE;
CREATE USER tcgatestinteg IDENTIFIED BY "1inttcg4"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO tcgatestinteg;

GRANT CREATE PROCEDURE TO tcgatestinteg;

GRANT CREATE SEQUENCE TO tcgatestinteg;

GRANT CREATE SESSION TO tcgatestinteg;

GRANT CREATE SYNONYM TO tcgatestinteg;

GRANT CREATE TABLE TO tcgatestinteg;

GRANT CREATE TRIGGER TO tcgatestinteg;

GRANT CREATE VIEW TO tcgatestinteg;


GRANT "CONNECT" TO tcgatestinteg;
ALTER USER tcgatestinteg DEFAULT ROLE NONE;

CREATE USER antannotportal IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antannotportal;

GRANT CREATE PROCEDURE TO antannotportal;

GRANT CREATE SEQUENCE TO antannotportal;

GRANT CREATE SESSION TO antannotportal;

GRANT CREATE SYNONYM TO antannotportal;

GRANT CREATE TABLE TO antannotportal;

GRANT CREATE TRIGGER TO antannotportal;

GRANT CREATE VIEW TO antannotportal;


GRANT "CONNECT" TO antannotportal;
ALTER USER antannotportal DEFAULT ROLE NONE;
CREATE USER antdamportal IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antdamportal;

GRANT CREATE PROCEDURE TO antdamportal;

GRANT CREATE SEQUENCE TO antdamportal;

GRANT CREATE SESSION TO antdamportal;

GRANT CREATE SYNONYM TO antdamportal;

GRANT CREATE TABLE TO antdamportal;

GRANT CREATE TRIGGER TO antdamportal;

GRANT CREATE VIEW TO antdamportal;


GRANT "CONNECT" TO antdamportal;
ALTER USER antdamportal DEFAULT ROLE NONE;
CREATE USER antqclvportal IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antqclvportal;

GRANT CREATE PROCEDURE TO antqclvportal;

GRANT CREATE SEQUENCE TO antqclvportal;

GRANT CREATE SESSION TO antqclvportal;

GRANT CREATE SYNONYM TO antqclvportal;

GRANT CREATE TABLE TO antqclvportal;

GRANT CREATE TRIGGER TO antqclvportal;

GRANT CREATE VIEW TO antqclvportal;


GRANT "CONNECT" TO antqclvportal;
ALTER USER antqclvportal DEFAULT ROLE NONE;
CREATE USER antdrepportal IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antdrepportal;

GRANT CREATE PROCEDURE TO antdrepportal;

GRANT CREATE SEQUENCE TO antdrepportal;

GRANT CREATE SESSION TO antdrepportal;

GRANT CREATE SYNONYM TO antdrepportal;

GRANT CREATE TABLE TO antdrepportal;

GRANT CREATE TRIGGER TO antdrepportal;

GRANT CREATE VIEW TO antdrepportal;


GRANT "CONNECT" TO antdrepportal;
ALTER USER antdrepportal DEFAULT ROLE NONE;
CREATE USER antuuidportal IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antuuidportal;

GRANT CREATE PROCEDURE TO antuuidportal;

GRANT CREATE SEQUENCE TO antuuidportal;

GRANT CREATE SESSION TO antuuidportal;

GRANT CREATE SYNONYM TO antuuidportal;

GRANT CREATE TABLE TO antuuidportal;

GRANT CREATE TRIGGER TO antuuidportal;

GRANT CREATE VIEW TO antuuidportal;


GRANT "CONNECT" TO antuuidportal;
ALTER USER antuuidportal DEFAULT ROLE NONE;
CREATE USER antannotcomm IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antannotcomm;

GRANT CREATE PROCEDURE TO antannotcomm;

GRANT CREATE SEQUENCE TO antannotcomm;

GRANT CREATE SESSION TO antannotcomm;

GRANT CREATE SYNONYM TO antannotcomm;

GRANT CREATE TABLE TO antannotcomm;

GRANT CREATE TRIGGER TO antannotcomm;

GRANT CREATE VIEW TO antannotcomm;


GRANT "CONNECT" TO antannotcomm;
ALTER USER antannotcomm DEFAULT ROLE NONE;
CREATE USER antdamcomm IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antdamcomm;

GRANT CREATE PROCEDURE TO antdamcomm;

GRANT CREATE SEQUENCE TO antdamcomm;

GRANT CREATE SESSION TO antdamcomm;

GRANT CREATE SYNONYM TO antdamcomm;

GRANT CREATE TABLE TO antdamcomm;

GRANT CREATE TRIGGER TO antdamcomm;

GRANT CREATE VIEW TO antdamcomm;


GRANT "CONNECT" TO antdamcomm;
ALTER USER antdamcomm DEFAULT ROLE NONE;
CREATE USER antdbrocomm IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antdbrocomm;

GRANT CREATE PROCEDURE TO antdbrocomm;

GRANT CREATE SEQUENCE TO antdbrocomm;

GRANT CREATE SESSION TO antdbrocomm;

GRANT CREATE SYNONYM TO antdbrocomm;

GRANT CREATE TABLE TO antdbrocomm;

GRANT CREATE TRIGGER TO antdbrocomm;

GRANT CREATE VIEW TO antdbrocomm;

CREATE USER antdbroportal IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antdbroportal;

GRANT CREATE PROCEDURE TO antdbroportal;

GRANT CREATE SEQUENCE TO antdbroportal;

GRANT CREATE SESSION TO antdbroportal;

GRANT CREATE SYNONYM TO antdbroportal;

GRANT CREATE TABLE TO antdbroportal;

GRANT CREATE TRIGGER TO antdbroportal;

GRANT CREATE VIEW TO antdbroportal;

CREATE USER antqclvcomm IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antqclvcomm;

GRANT CREATE PROCEDURE TO antqclvcomm;

GRANT CREATE SEQUENCE TO antqclvcomm;

GRANT CREATE SESSION TO antqclvcomm;

GRANT CREATE SYNONYM TO antqclvcomm;

GRANT CREATE TABLE TO antqclvcomm;

GRANT CREATE TRIGGER TO antqclvcomm;

GRANT CREATE VIEW TO antqclvcomm;


GRANT "CONNECT" TO antdbrocomm;
ALTER USER antdbrocomm DEFAULT ROLE NONE;
CREATE USER antuuidcomm IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antuuidcomm;

GRANT CREATE PROCEDURE TO antuuidcomm;

GRANT CREATE SEQUENCE TO antuuidcomm;

GRANT CREATE SESSION TO antuuidcomm;

GRANT CREATE SYNONYM TO antuuidcomm;

GRANT CREATE TABLE TO antuuidcomm;

GRANT CREATE TRIGGER TO antuuidcomm;

GRANT CREATE VIEW TO antuuidcomm;


GRANT "CONNECT" TO antuuidcomm;
ALTER USER antuuidcomm DEFAULT ROLE NONE;
CREATE USER antdrepcomm IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antdrepcomm;

GRANT CREATE PROCEDURE TO antdrepcomm;

GRANT CREATE SEQUENCE TO antdrepcomm;

GRANT CREATE SESSION TO antdrepcomm;

GRANT CREATE SYNONYM TO antdrepcomm;

GRANT CREATE TABLE TO antdrepcomm;

GRANT CREATE TRIGGER TO antdrepcomm;

GRANT CREATE VIEW TO antdrepcomm;


GRANT "CONNECT" TO antdrepcomm;
ALTER USER antdrepcomm DEFAULT ROLE NONE;
CREATE USER antdrepcomm IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antdrepcomm;

GRANT CREATE PROCEDURE TO antdrepcomm;

GRANT CREATE SEQUENCE TO antdrepcomm;

GRANT CREATE SESSION TO antdrepcomm;

GRANT CREATE SYNONYM TO antdrepcomm;

GRANT CREATE TABLE TO antdrepcomm;

GRANT CREATE TRIGGER TO antdrepcomm;

GRANT CREATE VIEW TO antdrepcomm;


GRANT "CONNECT" TO antdrepcomm;
ALTER USER antdrepcomm DEFAULT ROLE NONE;

CREATE USER qrtztest1 IDENTIFIED BY "qrtz1unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest1;

GRANT CREATE PROCEDURE TO qrtztest1;

GRANT CREATE SEQUENCE TO qrtztest1;

GRANT CREATE SESSION TO qrtztest1;

GRANT CREATE SYNONYM TO qrtztest1;

GRANT CREATE TABLE TO qrtztest1;

GRANT CREATE TRIGGER TO qrtztest1;

GRANT CREATE VIEW TO qrtztest1;


GRANT "CONNECT" TO qrtztest1;
ALTER USER qrtztest1 DEFAULT ROLE NONE;

CREATE USER qrtztest2 IDENTIFIED BY "qrtz2unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest2;

GRANT CREATE PROCEDURE TO qrtztest2;

GRANT CREATE SEQUENCE TO qrtztest2;

GRANT CREATE SESSION TO qrtztest2;

GRANT CREATE SYNONYM TO qrtztest2;

GRANT CREATE TABLE TO qrtztest2;

GRANT CREATE TRIGGER TO qrtztest2;

GRANT CREATE VIEW TO qrtztest2;


GRANT "CONNECT" TO qrtztest2;

CREATE USER qrtztest3 IDENTIFIED BY "qrtz3unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest3;

GRANT CREATE PROCEDURE TO qrtztest3;

GRANT CREATE SEQUENCE TO qrtztest3;

GRANT CREATE SESSION TO qrtztest3;

GRANT CREATE SYNONYM TO qrtztest3;

GRANT CREATE TABLE TO qrtztest3;

GRANT CREATE TRIGGER TO qrtztest3;

GRANT CREATE VIEW TO qrtztest3;


GRANT "CONNECT" TO qrtztest3;
ALTER USER qrtztest3 DEFAULT ROLE NONE;

CREATE USER qrtztest4 IDENTIFIED BY "qrtz4unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest4;

GRANT CREATE PROCEDURE TO qrtztest4;

GRANT CREATE SEQUENCE TO qrtztest4;

GRANT CREATE SESSION TO qrtztest4;

GRANT CREATE SYNONYM TO qrtztest4;

GRANT CREATE TABLE TO qrtztest4;

GRANT CREATE TRIGGER TO qrtztest4;

GRANT CREATE VIEW TO qrtztest4;


GRANT "CONNECT" TO qrtztest4;
ALTER USER qrtztest4 DEFAULT ROLE NONE;

CREATE USER qrtztest5 IDENTIFIED BY "qrtz5unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest5;

GRANT CREATE PROCEDURE TO qrtztest5;

GRANT CREATE SEQUENCE TO qrtztest5;

GRANT CREATE SESSION TO qrtztest5;

GRANT CREATE SYNONYM TO qrtztest5;

GRANT CREATE TABLE TO qrtztest5;

GRANT CREATE TRIGGER TO qrtztest5;

GRANT CREATE VIEW TO qrtztest5;


GRANT "CONNECT" TO qrtztest5;
ALTER USER qrtztest5 DEFAULT ROLE NONE;

CREATE USER qrtztest6 IDENTIFIED BY "qrtz6unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest6;

GRANT CREATE PROCEDURE TO qrtztest6;

GRANT CREATE SEQUENCE TO qrtztest6;

GRANT CREATE SESSION TO qrtztest6;

GRANT CREATE SYNONYM TO qrtztest6;

GRANT CREATE TABLE TO qrtztest6;

GRANT CREATE TRIGGER TO qrtztest6;

GRANT CREATE VIEW TO qrtztest6;


GRANT "CONNECT" TO qrtztest6;
ALTER USER qrtztest6 DEFAULT ROLE NONE;

CREATE USER qrtztest7 IDENTIFIED BY "qrtz7unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest7;

GRANT CREATE PROCEDURE TO qrtztest7;

GRANT CREATE SEQUENCE TO qrtztest7;

GRANT CREATE SESSION TO qrtztest7;

GRANT CREATE SYNONYM TO qrtztest7;

GRANT CREATE TABLE TO qrtztest7;

GRANT CREATE TRIGGER TO qrtztest7;

GRANT CREATE VIEW TO qrtztest7;


GRANT "CONNECT" TO qrtztest7;
ALTER USER qrtztest7 DEFAULT ROLE NONE;

CREATE USER qrtztest8 IDENTIFIED BY "qrtz8unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest8;

GRANT CREATE PROCEDURE TO qrtztest8;

GRANT CREATE SEQUENCE TO qrtztest8;

GRANT CREATE SESSION TO qrtztest8;

GRANT CREATE SYNONYM TO qrtztest8;

GRANT CREATE TABLE TO qrtztest8;

GRANT CREATE TRIGGER TO qrtztest8;

GRANT CREATE VIEW TO qrtztest8;


GRANT "CONNECT" TO qrtztest8;
ALTER USER qrtztest8 DEFAULT ROLE NONE;
CREATE USER qrtztest9 IDENTIFIED BY "qrtz9unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest9;

GRANT CREATE PROCEDURE TO qrtztest9;

GRANT CREATE SEQUENCE TO qrtztest9;

GRANT CREATE SESSION TO qrtztest9;

GRANT CREATE SYNONYM TO qrtztest9;

GRANT CREATE TABLE TO qrtztest9;

GRANT CREATE TRIGGER TO qrtztest9;

GRANT CREATE VIEW TO qrtztest9;


GRANT "CONNECT" TO qrtztest9;
ALTER USER qrtztest9 DEFAULT ROLE NONE;

CREATE USER qrtztest10 IDENTIFIED BY "qrtz10unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest10;

GRANT CREATE PROCEDURE TO qrtztest10;

GRANT CREATE SEQUENCE TO qrtztest10;

GRANT CREATE SESSION TO qrtztest10;

GRANT CREATE SYNONYM TO qrtztest10;

GRANT CREATE TABLE TO qrtztest10;

GRANT CREATE TRIGGER TO qrtztest10;

GRANT CREATE VIEW TO qrtztest10;


GRANT "CONNECT" TO qrtztest10;
ALTER USER qrtztest10 DEFAULT ROLE NONE;

CREATE USER qrtztest11 IDENTIFIED BY "qrtz11unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest11;

GRANT CREATE PROCEDURE TO qrtztest11;

GRANT CREATE SEQUENCE TO qrtztest11;

GRANT CREATE SESSION TO qrtztest11;

GRANT CREATE SYNONYM TO qrtztest11;

GRANT CREATE TABLE TO qrtztest11;

GRANT CREATE TRIGGER TO qrtztest11;

GRANT CREATE VIEW TO qrtztest11;


GRANT "CONNECT" TO qrtztest11;
ALTER USER qrtztest11 DEFAULT ROLE NONE;

CREATE USER qrtztest12 IDENTIFIED BY "qrtz12unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest12;

GRANT CREATE PROCEDURE TO qrtztest12;

GRANT CREATE SEQUENCE TO qrtztest12;

GRANT CREATE SESSION TO qrtztest12;

GRANT CREATE SYNONYM TO qrtztest12;

GRANT CREATE TABLE TO qrtztest12;

GRANT CREATE TRIGGER TO qrtztest12;

GRANT CREATE VIEW TO qrtztest12;


GRANT "CONNECT" TO qrtztest12;
ALTER USER qrtztest12 DEFAULT ROLE NONE;

CREATE USER qrtztest13 IDENTIFIED BY "qrtz13unit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO qrtztest13;

GRANT CREATE PROCEDURE TO qrtztest13;

GRANT CREATE SEQUENCE TO qrtztest13;

GRANT CREATE SESSION TO qrtztest13;

GRANT CREATE SYNONYM TO qrtztest13;

GRANT CREATE TABLE TO qrtztest13;

GRANT CREATE TRIGGER TO qrtztest13;

GRANT CREATE VIEW TO qrtztest13;


GRANT "CONNECT" TO qrtztest13;
ALTER USER qrtztest13 DEFAULT ROLE NONE;

CREATE USER antqrtz IDENTIFIED BY "antZ!h1LL"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO antqrtz;

GRANT CREATE PROCEDURE TO antqrtz;

GRANT CREATE SEQUENCE TO antqrtz;

GRANT CREATE SESSION TO antqrtz;

GRANT CREATE SYNONYM TO antqrtz;

GRANT CREATE TABLE TO antqrtz;

GRANT CREATE TRIGGER TO antqrtz;

GRANT CREATE VIEW TO antqrtz;


GRANT "CONNECT" TO antqrtz;

CREATE USER integqrtztest IDENTIFIED BY "1ntqrtzunit"
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT CREATE MATERIALIZED VIEW TO integqrtztest;

GRANT CREATE PROCEDURE TO integqrtztest;

GRANT CREATE SEQUENCE TO integqrtztest;

GRANT CREATE SESSION TO integqrtztest;

GRANT CREATE SYNONYM TO integqrtztest;

GRANT CREATE TABLE TO integqrtztest;

GRANT CREATE TRIGGER TO integqrtztest;

GRANT CREATE VIEW TO integqrtztest;
