Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1280, 'day_of_collection', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1281, 'month_of_collection', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1282, 'year_of_collection', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;      
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1283, 'day_of_sample_procurement', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1284, 'month_of_sample_procurement', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1285, 'year_of_sample_procurement', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1286, 'day_of_birth', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1287, 'month_of_birth', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1288, 'year_of_birth', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;   
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1289, 'day_of_last_known_alive', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1290, 'month_of_last_known_alive', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1291, 'year_of_last_known_alive', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');       
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1293, 'day_of_death', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');        
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1294, 'month_of_death', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');        
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1296, 'year_of_death', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');     
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1297, 'day_of_last_followup', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');     
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1298, 'month_of_last_followup', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1299, 'year_of_last_followup', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1300, 'day_of_initial_pathologic_diagnosis', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');        
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1301, 'month_of_initial_pathologic_diagnosis', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');     
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1302, 'day_of_form_completion', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N');     
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1303, 'month_of_form_completion', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1304, 'year_of_form_completion', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;

Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1305, 'day_of_tumor_progression', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1306, 'month_of_tumor_progression', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1307, 'year_of_tumor_progression', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1308, 'day_of_tumor_recurrence', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1309, 'month_of_tumor_recurrence', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1310, 'year_of_tumor_recurrence', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1311, 'day_of_procedure', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1312, 'month_of_procedure', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;
Insert into CLINICAL_XSD_ELEMENT (CLINICAL_XSD_ELEMENT_ID, ELEMENT_NAME, IS_PROTECTED, DESCRIPTION, VALUE_TYPE,EXPECTED_ELEMENT)Values(1313, 'year_of_procedure', 0, 'days elapsed from date of initial diagnosis to start of radiation treatment', 'string','N') ;


commit;
