function FileData_Pairs(x)
{
x.t("describes","tcga");
x.t("them.","topics");
x.t("anomalies","section");
x.t("anomalies","pathways");
x.t("anomalies","associated");
x.t("tcga","data");
x.t("gene","anomalies");
x.t("include:","viewing");
x.t("map","gene");
x.t("portal","prototype");
x.t("review","pathways");
x.t("viewing","pathways");
x.t("viewing","pathway");
x.t("section","describes");
x.t("section","include:");
x.t("pathways","anomalies");
x.t("pathways","associated");
x.t("prototype","review");
x.t("data","portal");
x.t("topics","section");
x.t("associated","them.");
x.t("associated","anomalies");
x.t("associated","abnormalities");
x.t("abnormalities","viewing");
x.t("pathway","map");
}
