function FileData_Pairs(x)
{
x.t("getting","started");
x.t("details","tcga");
x.t("determines","anomalies.");
x.t("results","application");
x.t("tcga","data");
x.t("include:","tcga");
x.t("introduces","tcga");
x.t("started","tcga");
x.t("portal","prototype");
x.t("section","include:");
x.t("section","introduces");
x.t("interpreting","results");
x.t("prototype","getting");
x.t("prototype","details");
x.t("prototype","determines");
x.t("prototype","section");
x.t("prototype","interpreting");
x.t("data","portal");
x.t("application","support");
x.t("topics","section");
x.t("anomalies.","topics");
}
