DROP TABLE qrtz_JOB_HISTORY;
CREATE TABLE QRTZ_JOB_HISTORY
(
  JOB_NAME           	VARCHAR2(200 BYTE)         NOT NULL,
  JOB_GROUP          	VARCHAR2(200 BYTE)         NOT NULL,
  FIRE_TIME         	DATE            NOT NULL,
  STATUS         	VARCHAR2(16)        NOT NULL,
  LAST_UPDATED         	DATE,
  JOB_DATA           	XMLTYPE,
  PRIMARY KEY (JOB_NAME,JOB_GROUP)
 )
XMLTYPE job_data STORE AS CLOB;
