ALTER TABLE patient ADD (
DAYSTOBIRTH NUMBER(38),
DAYSTODEATH NUMBER(38),
DAYSTOLASTFOLLOWUP NUMBER(38),
AGEATINITPATHOLOGICDIAGNOSIS NUMBER(38),
DAYSTOTUMORPROGRESSION NUMBER(38),
DAYSTOTUMORRECURRENCE NUMBER(38));

ALTER TABLE SAMPLE ADD(
DAYSTOCOLLECTION NUMBER(38))
ADD(
DAYSTODRUGTREATMENTSTART  NUMBER(38),
DAYSTODRUGTREATMENTEND NUMBER(38));

ALTER TABLE RADIATION ADD(
DAYSTORADIATIONTREATMENTSTART NUMBER(38),
DAYSTORADIATIONTREATMENTEND NUMBER(38));

ALTER TABLE EXAMINATION ADD(
DAYSTOEXAMINATION  NUMBER(38));

ALTER TABLE SURGERY ADD(
DAYSTOPROCEDURE  NUMBER(38));