ALTER TABLE GBMPATHOLOGY DROP CONSTRAINT GBMPATH_LEPTOMENINVOLE_CC;
ALTER TABLE GBMPATHOLOGY DROP CONSTRAINT GBMPATH_HNUCLEARGRADE_CC ;
ALTER TABLE GBMPATHOLOGY DROP CONSTRAINT GBMPATH_LEPTOMENINVOLE_CC; 
ALTER TABLE GBM_PATHOLOGY DROP CONSTRAINT GBMPATH_TANATOMICLOCATION_CC; 