CREATE TABLE L4_Anomaly_value_new 
PARTITION BY HASH(anomaly_data_set_id)
PARTITIONS 24
PARALLEL 2
AS SELECT * FROM l4_anomaly_value
nologging;
	
DROP TABLE l4_anomaly_value;

ALTER TABLE lr_Anomaly_Value_New RENAME TO L4_Anomaly_Value;

CREATE BITMAP INDEX L4_ANOMALYVAL_GE_IDX ON L4_ANOMALY_VALUE
(GENETIC_ELEMENT_ID)
LOCAL
COMPUTE STATISTICS;    
    
CREATE BITMAP INDEX L4_ANOMALYVAL_SAMPLE_IDX ON L4_ANOMALY_VALUE
(SAMPLE_ID)
LOCAL
COMPUTE STATISTICS;
	
	
CREATE UNIQUE INDEX L4_ANOMALYVAL_VALUE_IDX ON L4_ANOMALY_VALUE
(ANOMALY_VALUE, SAMPLE_ID, GENETIC_ELEMENT_ID, ANOMALY_DATA_SET_ID)
LOCAL
COMPUTE STATISTICS;
	
ALTER TABLE l4_anomaly_value LOGGING; 

	
