ALTER SESSION FORCE PARALLEL DDL;
ALTER INDEX PK_HYBRIDIZATION_VALUE REBUILD;
ALTER INDEX PK_COMPOSITE_ELEMENT REBUILD;
ALTER INDEX compe_ele_dsid_ceid_idx REBUILD;
ALTER INDEX composite_element_ak1 REBUILD;