ALTER SESSION FORCE PARALLEL DDL;
DROP INDEX L4_ANOMALYVAL_VALUE_IDX ;
CREATE UNIQUE INDEX L4_ANOMALYVAL_VALUE_IDX ON L4_ANOMALY_VALUE
(ANOMALY_VALUE, SAMPLE_ID, GENETIC_ELEMENT_ID, ANOMALY_DATA_SET_ID)
LOCAL
COMPUTE STATISTICS;
