---
abstract: 'check BCR XML and biotab files'
author:
  - 'Mark A. Jensen'
build_requires:
  IPC::Run: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: checkXmlBtab
provides:
  checkXmlBtab::Config:
    file: lib/checkXmlBtab/Config.pm
    version: v0.2.2
requires:
  XML::Twig: 0
version: v0.2.2
